/**
 * Custom Worker entry that wraps the OpenNext-generated handler so we can also
 * export our own Durable Object (AskRunDO). OpenNext copies a fixed worker
 * template that only re-exports its three internal DOs; to add a custom one we
 * re-export everything from the generated worker plus our class, and point
 * wrangler `main` here.
 */
// @ts-expect-error generated by `opennextjs-cloudflare build`
import handler, {
  // @ts-expect-error generated
  BucketCachePurge,
  // @ts-expect-error generated
  DOQueueHandler,
  // @ts-expect-error generated
  DOShardedTagCache,
} from "./.open-next/worker.js";

export { AskRunDO } from "./src/server/ask-run-do";
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache };
export default handler;
